In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.3 ms, sys: 4.42 ms, total: 19.8 ms
Wall time: 18.8 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 569 ms, sys: 108 ms, total: 676 ms
Wall time: 680 ms


## The NumPy ndarray: A multidimensional Array Object

In [6]:
import numpy as np

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[-1.92571389,  0.10797157, -2.91432266],
       [ 0.46047209,  1.18172028,  0.41773503]])

In [9]:
data * 10

array([[-19.25713885,   1.07971567, -29.1432266 ],
       [  4.60472087,  11.81720282,   4.17735029]])

In [10]:
data + data

array([[-3.85142777,  0.21594313, -5.82864532],
       [ 0.92094417,  2.36344056,  0.83547006]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

## Creating ndarrays

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[2.22766058e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data type for ndarrays

In [24]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [25]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2.dtype

dtype('int32')

In [28]:
arr = np.array([1, 2, 3, 4])

In [29]:
arr.dtype

dtype('int64')

In [30]:
arr = arr.astype(np.float64)

In [31]:
arr.dtype

dtype('float64')

In [32]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [33]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [34]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [35]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [36]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)

In [38]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [39]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
empty_uint32 = np.empty(8, dtype='u4')

In [41]:
empty_uint32

array([         0, 1072693248,          0, 1073741824,          0,
       1074266112,          0, 1074790400], dtype=uint32)

## Arithmetic with NumPy Arrays

In [42]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [43]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [47]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [48]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [49]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [50]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic indexing and slicing

In [51]:
arr = np.arange(10)

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8] = 12

In [56]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [57]:
arr_slice = arr[5:8]

In [58]:
arr_slice

array([12, 12, 12])

In [59]:
arr_slice[1] = 12345

In [60]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [61]:
arr_slice[:] = 64

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [63]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

3

In [66]:
arr2d[0, 2]

3

In [67]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [68]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
old_values = arr3d[0].copy()

In [72]:
arr3d[0] = 42

In [73]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr3d[0] = old_values

In [75]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Indexing with slices

In [76]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [77]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [78]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [81]:
arr2d[1, :2]

array([4, 5])

In [83]:
arr2d[:2, 2]

array([3, 6])

In [84]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [89]:
arr2d[:2, 1:] = 0

In [90]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 0, 0]])

In [91]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 0, 0]])

## Boolean Indexing

In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [93]:
data = np.random.randn(7, 4)

In [94]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [95]:
data

array([[-0.70432182, -0.538333  , -0.66827059, -1.60422606],
       [-0.17470501, -1.2508326 , -1.06428749,  1.94529069],
       [-2.46684428,  0.3274409 , -0.03138993,  0.76761755],
       [ 1.38082366, -0.10561972, -0.67192097,  1.78721932],
       [-0.19916733,  0.27640761,  0.92198754, -1.61690783],
       [ 0.64578045, -0.37719884,  0.07084508,  0.01928292],
       [-0.93394247, -1.45171512, -2.29315925,  1.30342912]])

In [96]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [98]:
data[names == 'Bob']

array([[-0.70432182, -0.538333  , -0.66827059, -1.60422606],
       [ 1.38082366, -0.10561972, -0.67192097,  1.78721932]])

In [100]:
data[ data < 0] = 0

In [101]:
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.94529069],
       [0.        , 0.3274409 , 0.        , 0.76761755],
       [1.38082366, 0.        , 0.        , 1.78721932],
       [0.        , 0.27640761, 0.92198754, 0.        ],
       [0.64578045, 0.        , 0.07084508, 0.01928292],
       [0.        , 0.        , 0.        , 1.30342912]])

In [102]:
data[names != 'Joe'] = 7

In [103]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 1.94529069],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.64578045, 0.        , 0.07084508, 0.01928292],
       [0.        , 0.        , 0.        , 1.30342912]])

## Fancy Indexing

In [104]:
arr = np.empty((8, 4))

In [105]:
for i in range(8):
    arr[i] = i

In [106]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [107]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [108]:
arr = np.arange(32).reshape((8, 4))

In [109]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [110]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [111]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

In [113]:
arr = np.arange(15).reshape((3, 5))

In [114]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [116]:
arr = np.random.randn(6, 3)

In [117]:
arr

array([[-0.80752886,  0.5609971 ,  0.30860471],
       [-1.43165149,  0.57658427, -1.37916362],
       [-2.71663262, -0.17517134, -1.32501509],
       [-1.39997889,  0.14699313,  1.30222794],
       [-0.18636567, -0.24826122,  0.68642313],
       [ 0.08673844, -0.10496126,  1.60474996]])

In [118]:
np.dot(arr.T, arr)

array([[12.08401823, -0.971237  ,  3.51302984],
       [-0.971237  ,  0.77210966, -0.5374033 ],
       [ 3.51302984, -0.5374033 ,  8.49519091]])

In [119]:
arr = np.arange(16).reshape((2, 2, 4))

In [120]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [122]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])